import { useState, useEffect } from "react";
import DealerPanel from "../components/gameplay/DealerPanel";
import AIViewButtons from "../components/gameplay/AIViewButtons";
import { cardImages } from "../assets/cards";
import ActiveCardPanel from "../components/gameplay/ActiveCardPanel";
import ViewPlayerButton from "../components/gameplay/ViewPlayerButton";
import PlayerOverlay from "../components/gameplay/overlays/PlayerOverlay";
import { Board } from "../game/Board";
import { BoardTile } from "../game/BoardTile";
import AIOverlay from "../components/gameplay/overlays/AIOverlay";
import { useGame } from "../context/useGame";
import { GameManager } from "../game/GameManager";
import { useNavigate } from "react-router-dom";
import { Card } from "../game/Card";

export default function GameplayPage(){
    const navigate = useNavigate();

    const { 
        gameConfig, 
        gameManager,
        setGameManager
    } = useGame();

    // initialize gameManager and enter Standby phase to start game
    useEffect(() => {
        if(!gameConfig){
            console.log("gameConfig is null!");
            return;
        }

        console.log("gameConfig: " , gameConfig);

        const manager = new GameManager(gameConfig);
        setGameManager(manager);
        manager.startGame();
    }, [gameConfig]);

    // subscribe the listeners
    useEffect(() => {
        if(!gameManager) return;

        const listener = () => {
            setDeckCount(gameManager.DeckCount);
            setCardsDrawnCount(gameManager.CardsDrawnCount);
            setActiveCard(gameManager.CurrentCard);
        }

        gameManager.subscribe(listener);

        const interval = setInterval(() => {
            setRoundTimer(gameManager.RemainingPlayTime);
        }, 1000);
        
        return() => {
            gameManager.unsubscribe(listener);
            clearInterval(interval);
        };
    }, [gameManager])

    // DealerPanel Props
    const [deckCount, setDeckCount] = useState(54);
    const [roundTimer, setRoundTimer] = useState(0);
    const [cardsDrawnCount, setCardsDrawnCount] = useState(0);
    const [activeCard, setActiveCard] = useState<Card>();

    // DealerPanel Props
    // const [roundTimer, setRoundTimer] = useState(configuration.pace);
    // const [deckCount, setDeckCount] = useState(53);
    // const [discardPileCount, setDiscardPile] = useState(0);

    // AIViewButtons Props
    const [overlayAIActive, setOverlayAIView] = useState([false, false, false, false]);
    const handleViewAIClick = (id: number) => {
        console.log(`ViewAIButton${id} clicked`);
        const newOverlayAIView = overlayAIActive.map((AIActive, i) => {
            if((i+1) === id){
                return !AIActive;
            }else{
                return AIActive;
            }
        });
        setOverlayAIView(newOverlayAIView);
    }
    console.log(`overlayAIActive: ${overlayAIActive}`);

    // dummy card to represent active card
    const randomIndex = Math.floor(Math.random()*54);

    // ActiveCardPanel Props
    // const [activeCard, setActiveCard] = useState(cardData[randomIndex]);

    // set AIPlayer count to 4
    const AIPlayerCount = 4;

    // ViewPlayerButton props
    const [overlayPlayerActive, setOverlayPlayerView] = useState(false);
    const handleViewPlayerClick = () => {
        console.log("ViewPlayerButton clicked");
        setOverlayPlayerView(!overlayPlayerActive);
    }
    console.log(`overlayPlayerActive: ${overlayPlayerActive}`);

    // PlayerOverlay Props

    // this board is the random board generated by the game logic
    // it will be connected from the game logic to here after completing UI
    // this random board definition is for UI purposes only
    const [playerBoard] = useState(new Board());
    const [aiBoards] = useState([
        new Board(), new Board(), new Board(), new Board()
    ]);

    // create array of BoardTile Grids 
    const aiBoardTileGrids = [
        extractBoardTileGrid(aiBoards[0]),
        extractBoardTileGrid(aiBoards[1]),
        extractBoardTileGrid(aiBoards[2]),
        extractBoardTileGrid(aiBoards[3])
    ];

    const [aiCardStateGrid] = useState(
        [[[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]
        ],
        [[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]
        ],
        [[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]
        ],
        [[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]]]
    );
    
    const [aiActiveCardToggleGrid] = useState([
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]
        ],
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]
        ],
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]
        ],
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]]
    ]);

    // create cardTile grid from player board
    const [playerBoardTileGrid] = useState(extractBoardTileGrid(playerBoard));

    // CardToggle props
    const [cardToggleGrid, setToggleGrid] = useState([
        [false, false, false, false],
        [false, false, false, false],
        [false, false, false, false],
        [false, false, false, false]
    ]);

    // CardToggle active prop
    const [activeCardToggleGrid, setActiveCardToggleGrid] = useState([
        [true, true, true, true],
        [true, true, true, true],
        [true, true, true, true],
        [true, true, true, true]
    ]);

    const handleToggleTile = (i: number, j: number) => {
        console.log(`Tile(${i}, ${j}) toggled!`);
        const newToggleGrid: boolean[][] = [];
        for(let row = 0; row <= 3; row++){
            const newToggleRow = [];
            for(let col = 0; col <= 3; col++){
                if((row === i) && (col === j)){
                    newToggleRow.push(!cardToggleGrid[row][col]);
                }else{
                    newToggleRow.push(cardToggleGrid[row][col]);
                }
            }
            newToggleGrid.push(newToggleRow);
        }

        // update cardToggleGrid state
        setToggleGrid(newToggleGrid);   
    }

    console.log(cardToggleGrid)

    // CallLoteriaButton prop
    const validLoteria = useState(true);

    const winnerData = {
        name: "Player",
        playerBoardTileGrid,
        cardToggleGrid,
        activeCardToggleGrid
    };

    const handleCallLoteria = () => {
        // if we have a valid call to Loteria
        if(validLoteria){
            console.log("Valid call to Loteria! Game over.");
            
            navigate("/gameover", {state: winnerData});

        }else{  // else incur penalty
            console.log("Invalid call to Loteria, penalty incurred.")
        }
    }


    return (
        <>
            <h1>GameplayPage</h1>
            <DealerPanel 
                roundTimer={roundTimer}
                deckCount={deckCount}
                discardPileCount={cardsDrawnCount}
            />
            <div className="mainGamePanel">
                <AIViewButtons 
                    onViewAIClick={handleViewAIClick}
                    AIPlayerCount={AIPlayerCount}
                />
                <ActiveCardPanel 
                    id={(activeCard===undefined)? 0 :activeCard.ID }
                    name={(activeCard===undefined)? "null":activeCard.Name}
                    description={(activeCard===undefined)? "null":activeCard.Description}
                    image={cardImages[(activeCard===undefined)? 0: activeCard.ID]}
                />
            </div>
            <ViewPlayerButton 
                onViewPlayerClick={handleViewPlayerClick}
            />
            {overlayPlayerActive && 
            <PlayerOverlay 
                boardTileGrid={playerBoardTileGrid}
                cardToggleGrid={cardToggleGrid}
                activeCardToggleGrid={activeCardToggleGrid}
                onToggleCard={handleToggleTile}
                onCallLoteria={handleCallLoteria}
            />}
            {overlayAIActive.map((overlayActive, i) => (
                overlayActive && 
                <AIOverlay 
                    key={i}
                    id={i} 
                    boardTileGrid={aiBoardTileGrids[i]}
                    cardToggleGrid={aiCardStateGrid[i]} 
                    activeCardToggleGrid={aiActiveCardToggleGrid[i]}
                />
            ))
            }
        </>
    );
}

// helper function to extract grid representing the cards within a board
export function extractBoardTileGrid(board: Board): BoardTile[][]{
    const boardTileGrid = [];
    // iterate through rows of Board
    for(let i = 0; i < 4; i++){
        const boardTileRow = [];

        // iterate through columns within row
        for(let j = 0; j < 4; j++){
            boardTileRow.push(board.getTile(i, j));
        }
        boardTileGrid.push(boardTileRow);
    }

    return boardTileGrid;
}