import { useState, useEffect } from "react";
import { useLocation } from "react-router-dom";
import DealerPanel from "../components/gameplay/DealerPanel";
import AIViewButtons from "../components/gameplay/AIViewButtons";
import cardData from "../data/cards.json";
import { cardImages } from "../assets/cards";
import ActiveCardPanel from "../components/gameplay/ActiveCardPanel";
import ViewPlayerButton from "../components/gameplay/ViewPlayerButton";
import PlayerOverlay from "../components/gameplay/overlays/PlayerOverlay";
import { Board } from "../game/Board";
import { BoardTile } from "../game/BoardTile";
import AIOverlay from "../components/gameplay/overlays/AIOverlay";

export default function GameplayPage(){
    const location = useLocation();
    const configuration = location.state;
    console.log(configuration);

    // const winCons = ["Row", "Column", "Diagonal", "Complete", "Pozo"];
    const winCons = useState(configuration.winCons);
    console.log(`winCons: ${winCons}`);

    // DealerPanel Props
    const [roundTimer, setRoundTimer] = useState(configuration.pace);
    const [deckCount, setDeckCount] = useState(53);
    const [discardPileCount, setDiscardPile] = useState(0);

    // AIViewButtons Props
    const [overlayAIActive, setOverlayAIView] = useState([false, false, false, false]);
    const handleViewAIClick = (id: number) => {
        console.log(`ViewAIButton${id} clicked`);
        const newOverlayAIView = overlayAIActive.map((AIActive, i) => {
            if((i+1) === id){
                return !AIActive;
            }else{
                return AIActive;
            }
        });
        setOverlayAIView(newOverlayAIView);
    }
    console.log(`overlayAIActive: ${overlayAIActive}`);

    // dummy card to represent active card
    const randomIndex = Math.floor(Math.random()*54);

    // ActiveCardPanel Props
    const [activeCard, setActiveCard] = useState(cardData[randomIndex]);

    // set AIPlayer count to 4
    const AIPlayerCount = 4;

    // ViewPlayerButton props
    const [overlayPlayerActive, setOverlayPlayerView] = useState(false);
    const handleViewPlayerClick = () => {
        console.log("ViewPlayerButton clicked");
        setOverlayPlayerView(!overlayPlayerActive);
    }
    console.log(`overlayPlayerActive: ${overlayPlayerActive}`);

    // PlayerOverlay Props

    // Board props
    // const dummyBoard = new Board();
    // const boardData = dummyBoard.

    // this board is the random board generated by the game logic
    // it will be connected from the game logic to here after completing UI
    // this random board definition is for UI purposes only
    const [playerBoard] = useState(new Board());
    const [aiBoards] = useState([
        new Board(), new Board(), new Board(), new Board()
    ]);

    // create arraty of BoardTile Grids 
    const aiBoardTileGrids = [
        extractBoardTileGrid(aiBoards[0]),
        extractBoardTileGrid(aiBoards[1]),
        extractBoardTileGrid(aiBoards[2]),
        extractBoardTileGrid(aiBoards[3])
    ];

    const [aiCardStateGrid] = useState(
        [[[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]
        ],
        [[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]
        ],
        [[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]
        ],
        [[false, false, false, false],
         [false, false, false, false],
         [false, false, false, false],
         [false, false, false, false]]]
    );
    
    const [aiActiveCardToggleGrid] = useState([
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]
        ],
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]
        ],
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]
        ],
        [[true, true, true, true],
         [true, true, true, true],
         [true, true, true, true],
         [true, true, true, true]]
    ]);

    // create cardTile grid from player board
    const playerBoardTileGrid = extractBoardTileGrid(playerBoard);

    // CardToggle props
    const [cardToggleGrid, setToggleGrid] = useState([
        [false, false, false, false],
        [false, false, false, false],
        [false, false, false, false],
        [false, false, false, false]
    ]);

    // CardToggle active prop
    const [activeCardToggleGrid, setActiveCardToggleGrid] = useState([
        [true, true, true, true],
        [true, true, true, true],
        [true, true, true, true],
        [true, true, true, true]
    ]);

    const handleToggleTile = (i: number, j: number) => {
        console.log(`Tile(${i}, ${j}) toggled!`);
        const newToggleGrid: boolean[][] = [];
        for(let row = 0; row <= 3; row++){
            const newToggleRow = [];
            for(let col = 0; col <= 3; col++){
                if((row === i) && (col === j)){
                    newToggleRow.push(!cardToggleGrid[row][col]);
                }else{
                    newToggleRow.push(cardToggleGrid[row][col]);
                }
            }
            newToggleGrid.push(newToggleRow);
        }

        // update cardToggleGrid state
        setToggleGrid(newToggleGrid);   
    }

    console.log(cardToggleGrid)

    return (
        <>
            <h1>GameplayPage</h1>
            {/* <h2>Configuration</h2>
            WinCons: 
            <ul>
            {configuration.winCons.map((winCon: boolean, i: number) => {
                return(
                    winCon ? <li>{winCons[i]}</li>: ""
                );
            })}
            </ul>
            Pace: {configuration.pace} */}
            <DealerPanel 
                roundTimer={roundTimer}
                deckCount={deckCount}
                discardPileCount={discardPileCount}
            />
            <div className="mainGamePanel">
                <AIViewButtons 
                    onViewAIClick={handleViewAIClick}
                    AIPlayerCount={AIPlayerCount}
                />
                <ActiveCardPanel 
                    id={activeCard.id}
                    name={activeCard.name}
                    description={activeCard.description}
                    image={cardImages[activeCard.id]}
                />
            </div>
            <ViewPlayerButton 
                onViewPlayerClick={handleViewPlayerClick}
            />
            {overlayPlayerActive && 
            <PlayerOverlay 
                boardTileGrid={playerBoardTileGrid}
                cardToggleGrid={cardToggleGrid}
                activeCardToggleGrid={activeCardToggleGrid}
                onToggleCard={handleToggleTile}
            />}
            {overlayAIActive.map((overlayActive, i) => {
                return(
                overlayActive && 
                <AIOverlay 
                    id={i + 1} 
                    rowArray={aiBoardTileGrids[i]}
                    cardToggleGrid={aiCardStateGrid[i]} 
                    activeCardToggleGrid={aiActiveCardToggleGrid[i]}
                />)
            })
            }
        </>
    );
}

// helper function to extract grid representing the cards within a board
function extractBoardTileGrid(board: Board): BoardTile[][]{
    const boardTileGrid = [];
    // iterate through rows of Board
    for(let i = 0; i < 4; i++){
        const boardTileRow = [];

        // iterate through columns within row
        for(let j = 0; j < 4; j++){
            boardTileRow.push(board.getTile(i, j));
        }
        boardTileGrid.push(boardTileRow);
    }

    return boardTileGrid;
}